DOMAIN,sso.douyin.com,DIRECT
DOMAIN,www.douyin.com,DIRECT
DOMAIN-KEYWORD,-core-c-hl,DIRECT
DOMAIN-KEYWORD,-core-c-lf,DIRECT
DOMAIN-KEYWORD,-normal-c-hl,DIRECT
DOMAIN-KEYWORD,-normal-c-lf,DIRECT
DOMAIN-KEYWORD,-normal-hl,DIRECT
DOMAIN-KEYWORD,-normal-lf,DIRECT
DOMAIN-KEYWORD,core-c-lq,DIRECT
DOMAIN-KEYWORD,core-lq,DIRECT
DOMAIN-KEYWORD,normal-c-lq,DIRECT
DOMAIN-KEYWORD,normal-lq,DIRECT
DOMAIN-KEYWORD,search-lq,DIRECT
DOMAIN-KEYWORD,search-quic-lq,DIRECT
DOMAIN-SUFFIX,snssdk.com,DIRECT